### ISSUE TITLE
consider using new versions of vcftools?

### ISSUE THREAD

**Issue by TomaszSuchan** [jpuritz/dDocent#28]
Hi Jon,
did you consider updating vcftools commands, so dDocent could use new versions of vcftools?
So far, I found these changes in `vcftools` flags to be made:
```
--geno to --max-missing
--missing to --missing-indv
```

Am I missing something?
I could make these changes if you want.

**Comment by jpuritz** [comment]
Hi Tomasz,

This has been on the todo list for a little while.  It’s a simple update to
dDocent, but also requires updating a tutorial and several other scripts.
I’ve also tried to avoid, as much as possible, to keep changing version and
installation requirements.  I’d probably go ahead and add a version check
with an if statement to provide the right command for the given version.
If you want to take a stab at this, please feel free to do so and submit a
pull request.

Thanks,

Jon

-- 
Jon Puritz, PhD
Postdoctoral Research Associate
Northeastern University
Marine Science Center
430 Nahant Rd, Nahant, MA 01908

Webpage: MarineEvoEco.com

Email:
jpuritz@gmail.com

Cell: 401-338-8739

"The most valuable of all talents is that of never using two words when one
will do."
-Thomas Jefferson


On November 30, 2016 at 2:19:22 PM, Tomasz Suchan (notifications@github.com)
wrote:

Hi Jon,
did you consider updating vcftools commands, so dDocent could use new
versions of vcftools?
So far, I found these changes in vcftools flags to be made:

--geno to --max-missing
--missing to --missing-indv

Am I missing something?
I could make these changes if you want.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jpuritz/dDocent/issues/28>, or mute the thread

**Comment by TomaszSuchan** [comment]
Hi Jon,
OK, I'll do this. I think the best way to deal with changing versions it is to keep the flag as a variable that changes the value according to the vcftools version.
Cheers,
Tomasz
