### ISSUE TITLE
PEAR is not accessible or licensed under a software iicense. Please consider substituting PANDAseq.

### ISSUE THREAD

**Issue by relshire** [jpuritz/dDocent#49]
Hi Jonathan,

As part of my work with the Genomics for Aotearoa New Zealand society, I am building docker containers for bioinformatics tools. It would be great to build a fully functional one for dDocent. Unfortunately, the PEAR software has two significant issues prohibiting inclusion. The first is that it is just not available in a way one can script up an install. The second is that it does not have a suitable license for software distribution.

On the other hand, PANDAseq is available from their github repo under free software licensing terms. https://github.com/neufeld/pandaseq It implements many algorithms, including the one used by PEAR. If you wouldn't mind substituting PANDAseq for PEAR, I would then be able to build a docker container of dDocent with full functionality.

Thank you for considering my request.

--Rob

**Comment by jpuritz** [comment]
Hi Rob,

Thanks for reaching out.  I'm reluctant to consider this change because it won't change any functionality for `dDocent`, it will instantly be incompatible with previous installs/environments, and will require time for implementation and testing.  It will also require time for getting users of previous versions up to speed.  

As far as I know, PEAR is distributed under the creative commons license that only prohibits commercial use.  See (https://cme.h-its.org/exelixis/web/software/pear/doc.html) and (http://www.exelixis-lab.org/pear).  It can be installed via `bioconda` which is my preferred environmental management system.  

That being said.  `PANDAseq` seems like a fine package, so I'm willing to consider it if you want to submit a pull request.  Even better if you can provide some testing.
