### ISSUE TITLE
awk program choice

### ISSUE THREAD

**Issue by wirawan0** [jpuritz/dDocent#57]
This is more of curiosity than issue. Why did dDocent restrict itself to using `mawk`? In an earlier version apparently gawk was supported, then dropped at commit 1310cbc. I would like to suggest using the more portable name (`awk`) if there is no absolute reason to use only `mawk`. I understand that `mawk` seems to be the fastest awk out there.

**Comment by jpuritz** [comment]
dDocent has always required `mawk` for the increased speed and efficiency.  Previous versions did utilize traditional `awk` as well for one function that has since been replaced.  Even though `awk` may seem more portable, there are still a lot of different versions out there, and sticking with only `mawk` makes things easier for development.
