### ISSUE TITLE
sh: /dev/tty: No such device or address

### ISSUE THREAD

**Issue by Anto007** [jpuritz/dDocent#86]
I consistently get the below error message when I run dDocent 2.8.13 (conda installation) on the SLURM-based computation cluster (CentOS Linux release 7.9.2009) at my end. The correct final output files seem to be created though. I was wondering if there were any quick-fix solutions here? Thank you very much.  

```
Using FreeBayes to call SNPs
sh: /dev/tty: No such device or address
```

**Comment by jpuritz** [comment]
The error message "sh: /dev/tty: No such device or address" typically occurs when a shell script or command tries to access the terminal device `/dev/tty`, but it's unable to find it. 

This could happen if the script is trying to read input from the terminal (`stdin`) but is unable to do so because the terminal device is not available or accessible.

Possible reasons for this error could include:

1. Running a script or command in a non-interactive environment where the terminal device is not available.
2. Permissions issue preventing access to the terminal device.
3. The terminal device being unavailable or misconfigured.

If you're running `dDocent` via SLURM, you need to make sure you are giving it a configuration file and not running interactively.
